online_auction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
]

user/urls.py
from django.urls import path

from .views import index, singup, singin, logout_view, account, edit_account

app_name = 'user'

urlpatterns = [
    path('', index, name='index'),
    path('singup', singup, name='singup'),
    path('singin', singin, name='singin'),
    path('logout_view', logout_view, name='logout_view'),
    path('account', account, name='account'),
    path('edit-account', edit_account, name='edit_account'),
]

item/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


def image_directory_path(instance, filename):
    return f'gallery/user_{instance.user.id}/{filename}'


class Item(models.Model):
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=500)
    photo = models.ImageField(upload_to=image_directory_path, null=True, blank=True)
    available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user', null=True, blank=True)

    def __str__(self):
        return self.name

user/models.py
from django.contrib.auth.models import User
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Account(models.Model):
    address = models.CharField(max_length=200, blank=True, null=True)
    phone = PhoneNumberField(blank=True, null=True)
    user_check = models.BooleanField(blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.username

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from phonenumber_field.formfields import PhoneNumberField
from .models import Account


class SingupForm(UserCreationForm):
    username = forms.CharField(max_length=100)
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = 'username', 'email', 'password1', 'password2'


class AccountForm(forms.ModelForm):
    # address = forms.CharField(max_length=250)
    # phone = PhoneNumberField()

    class Meta:
        model = Account
        fields = 'address', 'phone'


class SinginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = 'email',


class EditAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = 'address', 'phone'

item/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from .models import Account
from .forms import SingupForm, AccountForm, SinginForm, EditUserForm, EditAccountForm


def index(request):
    return render(request, 'user/index.html')


def singup(request):
    singup_form = SingupForm()
    account_form = AccountForm()
    if request.method == 'POST':
        singup_form = SingupForm(request.POST)
        account_form = AccountForm(request.POST)
        if singup_form.is_valid() and account_form.is_valid():
            user = singup_form.save()
            account = account_form.save(commit=False)
            account.user = user
            account.save()
            messages.success(request, 'successful create new user')
            return redirect(reverse('user:index'))
    return render(request, 'user/singup.html', {
        'singup_form': singup_form,
        'account_form': account_form,
    })


def singin(request):
    form = SinginForm()
    if request.method == 'POST':
        form = SinginForm(request.POST)
        if form.is_valid():
            user_name = form.cleaned_data['username']
            user = authenticate(request, username=user_name, password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'Success! Sing in')
                return redirect(reverse('user:index'))
            else:
                messages.error(request, 'Invalid username or password!')
        else:
            messages.error(request, 'Invalit input!')
    return render(request, 'user/singin.html', {
        'form': form,
    })


def logout_view(request):
    logout(request)
    return redirect(reverse('user:index'))


def account(request):
    return render(request, 'user/account.html')


def edit_account(request):
    user_form = EditUserForm(instance=request.user)
    account = Account.objects.get(user=request.user)
    account_form = EditAccountForm(instance=account)
    if request.method == 'POST':
        user_form = EditUserForm(request.POST, instance=request.user)
        account_form = EditAccountForm(request.POST, instance=account)
        if user_form.is_valid() and account_form.is_valid():
            user_form.save()
            account_form.user = request.user
            account_form.save()
            return redirect(reverse('user:account'))
    return render(request, 'user/edit_account.html', {
        'user_form': user_form,
        'account_form': account_form,
    })

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
        <title>Online Auction</title>
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav navbar-right">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:index' %}">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:account' %}">Login: {{ user }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:logout_view' %}">(login out)</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:singup' %}">Sing Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:singin' %}">Sing In</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        <div class="container my-3">
            {% block content %}
            {% endblock %}
        </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

user/templates/user/account.html
{% extends 'base.html' %}
{% block content %}

<h1>Account user</h1>
<p>User: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Address: {{ user.account.address }}</p>
<p>Phone: {{ user.account.phone }}</p>

<button><a href="{% url 'user:edit_account' %}">Edit account</a></button>

{% endblock %}

user/templates/user/edit_account.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ account_form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

user/templates/user/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Welcome to online auction</h1>
    <p>Please "create new account" or "sing in"</p>
{% endblock %}

user/templates/user/singin.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sing in</button>
    </form>
{% endblock %}

user/templates/user/singup.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create new user</h1>
    <form method="post" enctype="multipart/form-data">
        {{ user_form.non_field_errors }}
        {% csrf_token %}
        <div class="form-group">
            {{ singup_form.username.label_tag }}
            {{ singup_form.username }}
            <small id="usernameHelp" class="form-text text-muted">{{ singup_form.username.errors }}</small>
        </div>
        <div class="form-group">
            {{ singup_form.email.label_tag }}
            {{ singup_form.email }}
            <small id="emailHelp" class="form-text text-muted">{{ singup_form.email.errors }}</small>
        </div>
        <div class="form-group">
            {{ account_form.address.label_tag }}
            {{ account_form.address }}
            <small id="addressHelp" class="form-text text-muted">{{ account_form.address.errors }}</small>
        </div>
        <div class="form-group">
            {{ account_form.phone.label_tag }}
            {{ account_form.phone }}
            <small id="phoneHelp" class="form-text text-muted">{{ account_form.phone.errors }}</small>
        </div>
        <div class="form-group">
            {{ singup_form.password1.label_tag }}
            {{ singup_form.password1 }}
            <small id="emailHelp" class="form-text text-muted">{{ singup_form.password1.errors }}</small>
        </div>
        <div class="form-group">
            {{ singup_form.password2.label_tag }}
            {{ singup_form.password2 }}
            <small id="emailHelp" class="form-text text-muted">{{ singup_form.password2.errors }}</small>
        </div>
        <button type="submit">Create</button>
    </form>
{% endblock %}